/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMCommunities.java */

package goodman.com.sun.jmx.snmp.IPAcl;


import com.sun.jmx.snmp.IPAcl.AclEntryImpl;
import com.sun.jmx.snmp.IPAcl.JDMCommunity;
import com.sun.jmx.snmp.IPAcl.Node;
import com.sun.jmx.snmp.IPAcl.Parser;
import com.sun.jmx.snmp.IPAcl.SimpleNode;

class JDMCommunities extends com.sun.jmx.snmp.IPAcl.SimpleNode {
  JDMCommunities(int id) {
    super(id);
  }

  JDMCommunities(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
    super(p, id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
      return new JDMCommunities(id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
      return new JDMCommunities(p, id);
  }

  public void buildCommunities(com.sun.jmx.snmp.IPAcl.AclEntryImpl entry){
        for (int i =0 ; i < children.length ; i++)
          entry.addCommunity(((com.sun.jmx.snmp.IPAcl.JDMCommunity)children[i]).getCommunity());
  }
}
