/*
 * Copyright (c) 2000, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMInformInterestedHost.java */

package goodman.com.sun.jmx.snmp.IPAcl;

import com.sun.jmx.snmp.IPAcl.Node;
import com.sun.jmx.snmp.IPAcl.Parser;
import com.sun.jmx.snmp.IPAcl.SimpleNode;

class JDMInformInterestedHost extends com.sun.jmx.snmp.IPAcl.SimpleNode {
    JDMInformInterestedHost(int id) {
        super(id);
    }

    JDMInformInterestedHost(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new JDMInformInterestedHost(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        return new JDMInformInterestedHost(p, id);
    }
}
