/*
 * Copyright (c) 2000, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMInformItem.java */

package goodman.com.sun.jmx.snmp.IPAcl;

import com.sun.jmx.snmp.IPAcl.JDMInformCommunity;
import com.sun.jmx.snmp.IPAcl.Node;
import com.sun.jmx.snmp.IPAcl.Parser;
import com.sun.jmx.snmp.IPAcl.SimpleNode;

class JDMInformItem extends com.sun.jmx.snmp.IPAcl.SimpleNode {
    protected JDMInformCommunity comm = null;
    JDMInformItem(int id) {
        super(id);
    }

    JDMInformItem(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new JDMInformItem(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        return new JDMInformItem(p, id);
    }

    public JDMInformCommunity getCommunity(){
        return comm;
    }
}
