/*
 * Copyright (c) 2000, 2012, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMInformBlock.java */

package goodman.com.sun.jmx.snmp.IPAcl;

import com.sun.jmx.snmp.IPAcl.AclImpl;
import com.sun.jmx.snmp.IPAcl.Node;
import com.sun.jmx.snmp.IPAcl.Parser;
import com.sun.jmx.snmp.IPAcl.PrincipalImpl;
import com.sun.jmx.snmp.IPAcl.SimpleNode;

import goodman.java.net.InetAddress;
import goodman.java.util.Hashtable;
import goodman.java.util.Vector;

class JDMInformBlock extends com.sun.jmx.snmp.IPAcl.SimpleNode {
    JDMInformBlock(int id) {
        super(id);
    }

    JDMInformBlock(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new JDMInformBlock(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        return new JDMInformBlock(p, id);
    }

    /**
     * Do no need to go through this part of the tree for
     * building AclEntry.
     */
    @Override
    public void buildAclEntries(com.sun.jmx.snmp.IPAcl.PrincipalImpl owner, com.sun.jmx.snmp.IPAcl.AclImpl acl) {}

    /**
     * Do no need to go through this part of the tree for
     * building TrapEntry.
     */
    @Override
    public void buildTrapEntries(Hashtable<InetAddress, Vector<String>> dest) {}
}
