/*
 * Copyright (c) 2000, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMInformCommunity.java */

package goodman.com.sun.jmx.snmp.IPAcl;

import com.sun.jmx.snmp.IPAcl.Node;
import com.sun.jmx.snmp.IPAcl.Parser;
import com.sun.jmx.snmp.IPAcl.SimpleNode;

class JDMInformCommunity extends com.sun.jmx.snmp.IPAcl.SimpleNode {
    protected String community= "";
    JDMInformCommunity(int id) {
        super(id);
    }

    JDMInformCommunity(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new JDMInformCommunity(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        return new JDMInformCommunity(p, id);
    }

    public String getCommunity() {
        return community;
    }
}
