/*
 * Copyright (c) 1997, 2012, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMTrapBlock.java */

package goodman.com.sun.jmx.snmp.IPAcl;

import com.sun.jmx.snmp.IPAcl.AclImpl;
import com.sun.jmx.snmp.IPAcl.Node;
import com.sun.jmx.snmp.IPAcl.Parser;
import com.sun.jmx.snmp.IPAcl.PrincipalImpl;
import com.sun.jmx.snmp.IPAcl.SimpleNode;

import goodman.java.net.InetAddress;
import goodman.java.util.Hashtable;
import goodman.java.util.Vector;

class JDMTrapBlock extends com.sun.jmx.snmp.IPAcl.SimpleNode {
  JDMTrapBlock(int id) {
    super(id);
  }

  JDMTrapBlock(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
    super(p, id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
      return new JDMTrapBlock(id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
      return new JDMTrapBlock(p, id);
  }

  /**
   * Do no need to go through this part of the tree for
   * building AclEntry.
   */
   @Override
   public void buildAclEntries(PrincipalImpl owner, com.sun.jmx.snmp.IPAcl.AclImpl acl) {}

  /**
   * Do no need to go through this part of the tree for
   * building InformEntry.
   */
   @Override
   public void buildInformEntries(Hashtable<InetAddress, Vector<String>> dest) {}
}
