server:
  port: 8001

#TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
  path: /home/logs/paylogs
  file:
    max-history: 0
    max-size: 1MB
  level:
    root: INFO
    com.typc.iot.tgc: INFO

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.8.40.216:3306/cloud_dcim_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      read-only: false
      minimum-idle: 5  # 最小空闲连接数量
      idle-timeout: 60000  # 空闲连接存活最大时间，默认600000（10分钟）
      validation-timeout: 3000
      maximum-pool-size: 20  # 连接池最大连接数，默认是10
      auto-commit: true  # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: MyHikariCP # 连接池母子
      max-lifetime: 30000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      login-timeout: 5

tgs:
  databaseName: fotadev
# freemarker:
#   cache: false
# thymeleaf:
#   cache: false #html文件修改立即生效

generate:
  package: com.qunce
  generateAddress: F:\code